version: "3.7"

services:
  postgres:
    build: './database'
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
    restart: always
  nats: 
    image: "nats-streaming:0.9.2"
    restart: always
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    environment: 
      - "discovery.type=single-node"
  user:
    build: "."
    command: "user-service"
    depends_on: 
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
  user-client:
    build: "."
    command: "user-client-service"
    depends_on: 
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
  user-external-worker:
    build: "."
    command: "user-external-worker-service"
    depends_on: 
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
  user-of-client:
    build: "."
    command: "user-of-client-service"
    depends_on: 
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
  user-southpandas:
    build: "."
    command: "user-southpandas-service"
    depends_on: 
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
  query-user:
    build: "."
    command: "query-service-user"
    depends_on: 
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  query-user-client:
    build: "."
    command: "query-service-user-client"
    depends_on: 
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  query-user-external:
    build: "."
    command: "query-service-user-external"
    depends_on: 
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  query-user-of-client:
    build: "."
    command: "query-service-user-external"
    depends_on: 
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  query-user-southpandas:
    build: "."
    command: "query-service-user-external"
    depends_on: 
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: southpandas
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: southpandasdb
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  pusher:
    build: "."
    command: "pusher-service"
    depends_on: 
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"
  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - user
      - query
      - pusher